spring:
  application:
    name: product-service

server:
  port: 8081
  servlet:
    context-path: /product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
